# Site settings
title:       Козметиум
email:       
author:      
description: "Честный блог о красоте и здоровье"
baseurl:     ""
url:         "http://kozmetium.co"

# Google analytics
google_analytics: UA-59354803-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: kozmetium

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     6
sass:
  compressed: true
gems:
  - jekyll-sitemap
